[package]
name = "bevy_mod_inverse_kinematics"
version = "0.2.0"
authors = ["Bram Buurlage <brambuurlage@gmail.com>"]
edition = "2021"
categories = ["game-engines", "graphics", "rendering"]
description = "An inverse kinematics plugin for the Bevy engine."
repository = "https://github.com/Kurble/bevy_mod_inverse_kinematics/"
keywords = ["gamedev", "graphics", "bevy", "animation"]
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.9.0"
#bevy_prototype_debug_lines = { version = "0.9.1", features = ["3d"], optional = true }

[features]
#debug_lines = ["bevy_prototype_debug_lines"]